# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "50204c05fb0af49d92c69c48c4636e09"
name = "advanced-discount-rules"
application_url = "https://admin.shopify.com/store/ernm4z-cw/apps/advanced-discount-rules-2"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts"

[auth]
redirect_urls = [
  "https://shopify.dev/apps/default-app-home/api/auth",
  "http://localhost:3456/auth/callback",
  "http://localhost:3000/api/auth/callback",
  "https://admin.shopify.com/store/ernm4z-cw/apps/advanced-discount-rules-2/api/auth"
]

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = true
